
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label7;

	private global::Gtk.Label label6;

	private global::Gtk.SpinButton spbMaxInstr;

	private global::Gtk.SpinButton spbVhtSize;

	private global::Gtk.Label label5;

	private global::Gtk.SpinButton spbHistorySize;

	private global::Gtk.Label label4;

	private global::Gtk.SpinButton spbThreshold;

	private global::Gtk.Label label3;

	private global::Gtk.Label label2;

	private global::Gtk.SpinButton spbPerceptrons;

	private global::Gtk.ComboBox cbBenchmarks;

	private global::Gtk.Button btnSimulate;

	private global::Gtk.Label lInfo;

	private global::Gtk.Label label8;

	private global::Gtk.Label label1;

	private global::Gtk.Label lStatus;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Benchmarks");
		this.fixed1.Add(this.label7);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label7]));
		w1.X = 30;
		w1.Y = 19;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Max Instr");
		this.fixed1.Add(this.label6);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
		w2.X = 32;
		w2.Y = 222;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spbMaxInstr = new global::Gtk.SpinButton(0D, 90000000000D, 100000D);
		this.spbMaxInstr.WidthRequest = 200;
		this.spbMaxInstr.CanFocus = true;
		this.spbMaxInstr.Name = "spbMaxInstr";
		this.spbMaxInstr.Adjustment.PageIncrement = 10D;
		this.spbMaxInstr.ClimbRate = 100000D;
		this.spbMaxInstr.Numeric = true;
		this.spbMaxInstr.Value = 50000D;
		this.fixed1.Add(this.spbMaxInstr);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spbMaxInstr]));
		w3.X = 131;
		w3.Y = 217;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spbVhtSize = new global::Gtk.SpinButton(0D, 16384D, 1D);
		this.spbVhtSize.WidthRequest = 100;
		this.spbVhtSize.CanFocus = true;
		this.spbVhtSize.Name = "spbVhtSize";
		this.spbVhtSize.Adjustment.PageIncrement = 10D;
		this.spbVhtSize.ClimbRate = 1D;
		this.spbVhtSize.Numeric = true;
		this.spbVhtSize.Value = 512D;
		this.fixed1.Add(this.spbVhtSize);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spbVhtSize]));
		w4.X = 131;
		w4.Y = 178;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("VHT Size");
		this.fixed1.Add(this.label5);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
		w5.X = 34;
		w5.Y = 185;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spbHistorySize = new global::Gtk.SpinButton(0D, 512D, 1D);
		this.spbHistorySize.WidthRequest = 100;
		this.spbHistorySize.CanFocus = true;
		this.spbHistorySize.Name = "spbHistorySize";
		this.spbHistorySize.Adjustment.PageIncrement = 1D;
		this.spbHistorySize.ClimbRate = 1D;
		this.spbHistorySize.Numeric = true;
		this.spbHistorySize.SnapToTicks = true;
		this.spbHistorySize.Value = 32D;
		this.fixed1.Add(this.spbHistorySize);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spbHistorySize]));
		w6.X = 129;
		w6.Y = 136;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("History Size");
		this.fixed1.Add(this.label4);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
		w7.X = 32;
		w7.Y = 145;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spbThreshold = new global::Gtk.SpinButton(0D, 200D, 1D);
		this.spbThreshold.CanFocus = true;
		this.spbThreshold.Name = "spbThreshold";
		this.spbThreshold.Adjustment.PageIncrement = 10D;
		this.spbThreshold.ClimbRate = 1D;
		this.spbThreshold.Numeric = true;
		this.spbThreshold.Value = 10D;
		this.fixed1.Add(this.spbThreshold);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spbThreshold]));
		w8.X = 129;
		w8.Y = 95;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Threshold");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w9.X = 31;
		w9.Y = 101;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Perceptrons");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w10.X = 31;
		w10.Y = 59;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spbPerceptrons = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spbPerceptrons.CanFocus = true;
		this.spbPerceptrons.Name = "spbPerceptrons";
		this.spbPerceptrons.Adjustment.PageIncrement = 10D;
		this.spbPerceptrons.ClimbRate = 1D;
		this.spbPerceptrons.Numeric = true;
		this.spbPerceptrons.Value = 10D;
		this.fixed1.Add(this.spbPerceptrons);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.spbPerceptrons]));
		w11.X = 129;
		w11.Y = 55;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.cbBenchmarks = global::Gtk.ComboBox.NewText();
		this.cbBenchmarks.WidthRequest = 200;
		this.cbBenchmarks.Name = "cbBenchmarks";
		this.fixed1.Add(this.cbBenchmarks);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cbBenchmarks]));
		w12.X = 127;
		w12.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSimulate = new global::Gtk.Button();
		this.btnSimulate.CanFocus = true;
		this.btnSimulate.Name = "btnSimulate";
		this.btnSimulate.UseUnderline = true;
		this.btnSimulate.Relief = ((global::Gtk.ReliefStyle)(1));
		this.btnSimulate.Label = global::Mono.Unix.Catalog.GetString("Simulate");
		this.fixed1.Add(this.btnSimulate);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnSimulate]));
		w13.X = 158;
		w13.Y = 313;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lInfo = new global::Gtk.Label();
		this.lInfo.Name = "lInfo";
		this.lInfo.LabelProp = global::Mono.Unix.Catalog.GetString(".");
		this.fixed1.Add(this.lInfo);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lInfo]));
		w14.X = 59;
		w14.Y = 291;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Info :");
		this.fixed1.Add(this.label8);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label8]));
		w15.X = 15;
		w15.Y = 290;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Status");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w16.X = 14;
		w16.Y = 258;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lStatus = new global::Gtk.Label();
		this.lStatus.Name = "lStatus";
		this.lStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Waiting");
		this.fixed1.Add(this.lStatus);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lStatus]));
		w17.X = 81;
		w17.Y = 257;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 416;
		this.DefaultHeight = 365;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.spbVhtSize.ValueChanged += new global::System.EventHandler(this.VhtSizeValueChanged);
		this.btnSimulate.Clicked += new global::System.EventHandler(this.BtnSimulateClick);
	}
}
